version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/crackit
    volumes:
      - ./server:/app
    depends_on:
      - mongo
    restart: unless-stopped

  client:
    build:
      context: ./client
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mongo-data:
