name: Client CI

on:
  push:
    branches: [ main ]
    paths:
      - 'client/**'
      - '.github/workflows/client.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'client/**'
      - '.github/workflows/client.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./client

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './client/package.json'
    
    - name: Install Dependencies
      run: npm install
      
    - name: Lint
      run: npm run lint
      
    - name: Build
      run: npm run build
      env:
        VITE_GOOGLE_API_KEY: ${ secrets.VITE_GOOGLE_API_KEY }
      
    - name: Test
      run: npm test --if-present
